### ISSUE TITLE
More convenient to use environment variables

### ISSUE THREAD

**Issue by ghost** [erikthalen/visitor-counter#3]
For the followings:

`mongourl` and `dbName`
https://github.com/erikthalen/visitor-counter/blob/c98ed3d639c67ad1d491d2b291877ed471ef5bb6/lib/db.js#L4

`COOKIE_KEY`
https://github.com/erikthalen/visitor-counter/blob/c98ed3d639c67ad1d491d2b291877ed471ef5bb6/lib/index.js#L10

**Comment by erikthalen** [comment]
In general some of the variables, like f.ex. `COOKIE_KEY`, isn't something the user will interact with. And the options parameters you can of course pass a env variable as value:
```js
const stats = visitorCounter({ mongourl: process.env.MY_URL })
```

But for v0.1.0 i've placed all variables in the options object. So if they really need to change, it's now possible.
