### ISSUE TITLE
Use ` fast-geoip` instead of `GeoIP-lite`

### ISSUE THREAD

**Issue by ghost** [erikthalen/visitor-counter#4]
**GeoIP-lite** says:

> On average, an IP to Location lookup should take 20 microseconds on a Macbook Pro. IPv4 addresses take about 6 microseconds, while IPv6 addresses take about 30 microseconds.

Which is a lot to my opinion for a user tracker !!!! really a lot. That makes it unpractical. Plus they don't offer asynchronous calls which is a disaster (getting from disk synchronously for each request is just not useful).

**fast-geoip** appeas to be:

In-memory, so slower startup but generally who cares ? but very fast subsequent lookups. I would definitly go for `fast-geoip`, plus I will open an issue there for an async version.

**Comment by erikthalen** [comment]
Good call. Changed to fast-geoip for v0.1.0
