### ISSUE TITLE
Flushing visitors map

### ISSUE THREAD

**Issue by ghost** [erikthalen/visitor-counter#5]
So `visitors` is an in-memory Map, particularly `visitors#flush` is called in `index` so only once when importing the library ?

It would be better to have the `ttl` in an environment variable, and simply set that index in MongoDB, as it manages that (asynchronously, and continuously) [check doc](https://docs.mongodb.com/v3.4/core/index-ttl/)

And then you can keep `visitors` map synchronised simply by a timer like `setTimeout`.

**Comment by erikthalen** [comment]
This is great! Didn't know mongo db had a feature like that. For v0.1.0 i've removed the in-memory map, and changed it to using a time-limited-index to keep track of the current visitors.
