### ISSUE TITLE
Provide a mongoDB instance beforehand

### ISSUE THREAD

**Issue by ghost** [erikthalen/visitor-counter#7]
I'm already integrating `visitor-counter` on my [project](https://github.com/bacloud22/visitor-counter). Thanks a lot @erikthalen !

Because my app is Fastify based, I have a shared DB connexion all over the app, generally `visitor-counter` works well, but sometimes (undetermined) it makes node crash, because of database interference. This is the error on windows, and I can't figure out when it throws:

> 
> C:\Users\Administrator\Documents\classifier-ads-project\listings\node_modules\mongodb\lib\cmap\connection.js:462
>                     callback(new error_1.MongoServerError(document));
>                              ^
> 
> MongoServerError: cannot perform operation: a background operation is currently running for collection listings_db.visitors-default-current
>     at MessageStream.messageHandler (C:\Users\Administrator\Documents\classifier-ads-project\listings\node_modules\mongodb\lib\cmap\connection.js:462:30)
>     ..................

If providing a DB instance on the top most API is feasibly and easy, (I know this requires a rewrite of db.js API a little), it would be very appreciated.

Something like:
```js
  mongourl = 'mongodb://localhost:27017/',
  dbName = 'visitor-counter-db',
  ttl = 3600,
  id = 'default',
  cookieKey = 'visitor-counter-id',
  preMongoDB = undefined,
} = {}) => {
  let database
  if (preMongoDB) {
    database = await db({ id, mongourl, dbName, ttl, preMongoDB })
  } else {
    database = await db({ id, mongourl, dbName, ttl })
  }
```

(I'm not the best in API and libraries, so..).

I could try to work on this if you like and don't have time for this.. (but i'm not the best x))

**Comment by erikthalen** [comment]
I'm no expert either..! I've pushed `1.0.7` where all calls to the db is wrapped in try-catch's. Hopefully the runtime wont crash and die at least.. Let's see.

You're more than welcome to make any contributions! That would be cool.

**Comment by ghost** [comment]
cool, now let's see what errors and when; I will try to spot and reproduce if anything raises !
thanks for follow  up
